image: node

stages:
  - test
  - build
  - deploy

build site-recaptcha:
  stage: build
  cache:
    key: site-package
    policy: push
    paths:
      - ./build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 1 hr
    paths:
      - ./build
  before_script:
    - ls ./build
  script:
    - npm i
    - npm run build
  after_script:
    - ls ./build

deploy site-recaptcha:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
  before_script:
    - ls ./build
  script:
    - npx surge --project ./build --domain recaptcha.angelomedeiros.surge.sh
  after_script:
    - ls ./build
