image: node

stages:
  - test
  - build
  - deploy

build site-recaptcha:
  stage: build
  cache:
    key: site-package
    policy: push
    paths:
      - ./
  before_script:
    - ls
  script:
    - npm i
    - npm run build
  after_script:
    - ls

deploy site-recaptcha:
  stage: deploy
  # variables:
  #   GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
  before_script:
    - ls
  script:
    - npx surge --project ./build --domain recaptcha.angelomedeiros.surge.sh
  after_script:
    - ls
