image: node

build site-recaptcha:
  stage: build
  cache:
    key: site-build
    policy: push
    paths:
      - ./build
  script:
    - ls
    - npm i
    - npm run build
    - ls

deploy site-recaptcha:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  cache:
    key: site-build
    policy: pull
  script:
    - ls
    - npx surge --project ./build --domain recaptcha.angelomedeiros.surge.sh
